language: ruby

rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.2
 - 2.2.0
 - 2.3.1
 - 2.4.0
 - 3.2.3
 - jruby-19mode # JRuby in 1.9 mode
 - ruby-head

env:
 - NENDO_CLEAN_TEST=0
# - NENDO_CLEAN_TEST=1

gemfile:
 - gemfiles/Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
