# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nendo}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kiyoka Nishiyama"]
  s.date = %q{2010-11-14}
  s.default_executable = %q{nendo}
  s.description = %q{Nendo is a programming language written in Ruby.}
  s.email = %q{kiyoka@sumibi.org}
  s.executables = ["nendo"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "benchmark/benchmark.nnd",
     "benchmark/nendo_benchmark_code.nnd",
     "benchmark/ruby_benchmark_code.rb",
     "bin/nendo",
     "emacs/nendo-mode.el",
     "example/KyotoCabinet/kcbench.rb",
     "example/KyotoCabinet/kcbench1.nnd",
     "example/KyotoCabinet/kcbench2.nnd",
     "example/KyotoCabinet/kcbench3.nnd",
     "example/KyotoCabinet/kcsample.nnd",
     "example/KyotoCabinet/kcsample.rb",
     "example/cgi/dekamoji.cgi",
     "example/cgi/sample.cgi",
     "example/deep-loop1.nnd",
     "example/deep-loop2.nnd",
     "example/exit.nnd",
     "example/export-lisp-functions.rb",
     "example/fact.nnd",
     "example/fizzbuzz1.nnd",
     "example/html-lite-sample.nnd",
     "example/nqueen.nnd",
     "example/scratch.nnd",
     "example/twitterTL.nnd",
     "lib/debug/syslog.nnd",
     "lib/debug/syslog.nndc",
     "lib/init.nnd",
     "lib/init.nndc",
     "lib/nendo.rb",
     "lib/nendo/test.nnd",
     "lib/nendo/test.nndc",
     "lib/srfi-1.nnd",
     "lib/srfi-1.nndc",
     "lib/text/html-lite.nnd",
     "lib/text/html-lite.nndc",
     "lib/text/tree.nnd",
     "lib/text/tree.nndc",
     "test/nendo_spec.rb",
     "test/nendo_util.nnd",
     "test/srfi-1-test.nnd",
     "test/textlib.nnd"
  ]
  s.homepage = %q{http://github.com/kiyoka/nendo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Nendo is a dialect of Lisp.}
  s.test_files = [
    "test/nendo_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

