#!/usr/local/bin/ruby -W0
#
# Nendo:   "Principle of Least Surprise (for Rubyist)"
#
#
# How to shebang:
#   start script file as
#               #!/bin/sh
#               true; #-*- mode: nendo; syntax: scheme -*-;;
#               true; exec /usr/local/bin/nendo "$0"
#                   .
#                   .
#
require 'nendo/nendo'

def main
  core = Nendo.new()
  core.loadInitFile
  if 0 < ARGV.length
    core.load( ARGV[0] )
  else
    core.repl
  end
end

main
