# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "nendo"
  s.version = "0.6.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kiyoka Nishiyama"]
  s.date = "2012-02-17"
  s.description = "Nendo is a programming language written in Ruby."
  s.email = "kiyoka@sumibi.org"
  s.executables = ["nendo"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gemtest",
    "History.txt",
    "Rakefile",
    "VERSION.yml",
    "benchmark/benchmark.nnd",
    "benchmark/nendo_benchmark_code.nnd",
    "benchmark/ruby_benchmark_code.rb",
    "bin/nendo",
    "emacs/nendo-mode.el",
    "example/KyotoCabinet/kcbench.rb",
    "example/KyotoCabinet/kcbench1.nnd",
    "example/KyotoCabinet/kcbench2.nnd",
    "example/KyotoCabinet/kcbench3.nnd",
    "example/KyotoCabinet/kcsample.nnd",
    "example/KyotoCabinet/kcsample.rb",
    "example/cgi/dekamoji.cgi",
    "example/cgi/sample.cgi",
    "example/deep-loop1.nnd",
    "example/deep-loop2.nnd",
    "example/exit.nnd",
    "example/export-lisp-functions.rb",
    "example/fact.nnd",
    "example/fizzbuzz1.nnd",
    "example/html-lite-sample.nnd",
    "example/nqueen.nnd",
    "example/twitterTL.nnd",
    "lib/nendo.rb",
    "lib/nendo/debug/syslog.nnd",
    "lib/nendo/debug/syslog.nndc",
    "lib/nendo/init.nnd",
    "lib/nendo/init.nndc",
    "lib/nendo/nendo/experimental.nnd",
    "lib/nendo/nendo/experimental.nndc",
    "lib/nendo/nendo/test.nnd",
    "lib/nendo/nendo/test.nndc",
    "lib/nendo/rfc/json.nnd",
    "lib/nendo/rfc/json.nndc",
    "lib/nendo/ruby/builtin_functions.rb",
    "lib/nendo/ruby/core.rb",
    "lib/nendo/ruby/evaluator.rb",
    "lib/nendo/ruby/out_of_module.rb",
    "lib/nendo/ruby/printer.rb",
    "lib/nendo/ruby/reader.rb",
    "lib/nendo/ruby/types.rb",
    "lib/nendo/srfi-1.nnd",
    "lib/nendo/srfi-1.nndc",
    "lib/nendo/srfi-2.nnd",
    "lib/nendo/srfi-2.nndc",
    "lib/nendo/srfi-26.nnd",
    "lib/nendo/srfi-26.nndc",
    "lib/nendo/text/html-lite.nnd",
    "lib/nendo/text/html-lite.nndc",
    "lib/nendo/text/tree.nnd",
    "lib/nendo/text/tree.nndc",
    "lib/nendo/util/combinations.nnd",
    "lib/nendo/util/combinations.nndc",
    "lib/nendo/util/list.nnd",
    "lib/nendo/util/list.nndc",
    "lib/nendo/util/match.nnd",
    "lib/nendo/util/match.nndc",
    "test/json-test.nnd",
    "test/match-test.nnd",
    "test/nendo-util-test.nnd",
    "test/nendo_spec.rb",
    "test/rspec_formatter_for_emacs.rb",
    "test/srfi-1-test.nnd",
    "test/srfi-2-test.nnd",
    "test/srfi-26-test.nnd",
    "test/syntax_spec.rb",
    "test/testframework_spec.rb",
    "test/textlib-test.nnd",
    "test/util-combinations-test.nnd",
    "test/util-list-test.nnd"
  ]
  s.homepage = "http://github.com/kiyoka/nendo"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Nendo is a dialect of Lisp."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
  end
end

