#!/usr/bin/env ruby
#
# Nendo:   "Principle of Least Surprise (for Rubyist)"
#  
#
#
require 'nendo'

def main
  if "-t" == ARGV[0] 
    testSequence
  elsif 0 < ARGV.length
    core = Nendo.new
    core.loadInitFile
    core.loadFile( ARGV[0] )
  else
    core = Nendo.new
    core.repl
  end
end

main
