#!/usr/bin/env ruby
#
# Nendo:   "Principle of Least Surprise (for Rubyist)"
#  
#
#
require 'nendo'

def main
  core = Nendo.new
  core.loadInitFile
  if 0 < ARGV.length
    core.loadFile( ARGV[0] )
  else
    core.repl
  end
end

main
