#!/bin/sh
:; #-*- mode: nendo; syntax: scheme -*-;;
:; exec /usr/local/bin/nendo $0 $*
;;
;; nendoc  -  "nendo compiling utility"
;;  
;;   Copyright (c) 2010-2010  Kiyoka Nishiyama  <kiyoka@sumibi.org>
;;   
;;   Redistribution and use in source and binary forms, with or without
;;   modification, are permitted provided that the following conditions
;;   are met:
;;   
;;   1. Redistributions of source code must retain the above copyright
;;      notice, this list of conditions and the following disclaimer.
;;  
;;   2. Redistributions in binary form must reproduce the above copyright
;;      notice, this list of conditions and the following disclaimer in the
;;      documentation and/or other materials provided with the distribution.
;;  
;;   3. Neither the name of the authors nor the names of its contributors
;;      may be used to endorse or promote products derived from this
;;      software without specific prior written permission.
;;  
;;   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
;;   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
;;   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
;;   A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
;;   OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
;;   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
;;   TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
;;   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
;;   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
;;   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;;  
;;  $Id: 
;;
;;
(clean-compiled-code)

(define (compiled-code-string compiled-code filename)
  (+ 
   (string-join
    `("#!/usr/local/bin/ruby"
      "# -*- encoding: utf-8 -*-"
      "#"
      "# -------------------------------------------------------"
      ,(sprintf "#   This file compiled from source [%s] " filename )
      "# -------------------------------------------------------"
      "#"
      "")
    "\n")

   (string-join
    (assv-ref filename compiled-code)
    "\n#--------------------\n")

   (string-join
    `("\n\n"
      "# -------------------------------------------------------"
      "# [EOF]"
      "# -------------------------------------------------------")
    "\n")))
    
(define (main argv)
  (cond
   ((zero? (length argv))
    (print
     (+ "Usage : nendoc xxxx.nnd \n"
        "        xxxx.nnd is user source file to compile.\n")))
   (else
    (for-each
     (lambda (fn)
       (when (not (File.exist? fn))
         (errorf "Error: file [%s] not found." fn)
         (exit 1))
       (load fn)
       (with-open (+ fn "c")
                  (lambda (f)
                    (f.puts (compiled-code-string (get-compiled-code) fn)))
                  "w"))
     argv)))
  (exit 0))

(main *argv*)
