name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.0'
          - '2.1'
          - '2.2'
          - '2.3'
          - '2.4'
          - '3.2.3'
          - 'jruby'
          - 'head'
        env:
          - NENDO_CLEAN_TEST=0
        include:
          - ruby-version: 'head'
            continue-on-error: true

    env:
      NENDO_CLEAN_TEST: ${{ matrix.env }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        working-directory: ./gemfiles

    - name: Run tests
      run: bundle exec rake
      working-directory: ./gemfiles
      continue-on-error: ${{ matrix.ruby-version == 'head' }}